FROM node:21.7.0-alpine3.19 AS development

ARG NODE_ENV
ENV NODE_ENV=$NODE_ENV

WORKDIR /home/nels/app

COPY app/package*.json ./

RUN npm i

COPY app/ ./

RUN npm run build

RUN if [ "$NODE_ENV" != "dev" ]; then npm prune --production; fi


FROM nginx:stable-alpine3.17 as production

COPY --from=development /home/nels/app/dist /usr/share/nginx/html/

COPY docker/setup/certificate.pem /home/nels/certificate.pem
COPY docker/setup/private_key.pem /home/nels/private_key.pem
COPY docker/setup/default.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
EXPOSE 443

CMD ["nginx", "-g", "daemon off;"]
